<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.24.1" />
    <PackageReference Include="Grpc.Tools" Version="2.57.0">
      <PrivateAssets>All</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="../../proto/livesplit/bridge/v2/common.proto" ProtoRoot="../../proto" />
    <Protobuf Include="../../proto/livesplit/bridge/v2/run.proto" ProtoRoot="../../proto" />
    <Protobuf Include="../../proto/livesplit/bridge/v2/bridge.proto" ProtoRoot="../../proto" />
    <Protobuf Include="../../proto/livesplit/bridge/v3/common.proto" ProtoRoot="../../proto" />
    <Protobuf Include="../../proto/livesplit/bridge/v3/run.proto" ProtoRoot="../../proto" />
    <Protobuf Include="../../proto/livesplit/bridge/v3/bridge.proto" ProtoRoot="../../proto" />
  </ItemGroup>

</Project>
