<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference
      Include="..\..\external\LiveSplit\src\LiveSplit.Core\LiveSplit.Core.csproj"
      Private="false"
      ExcludeAssets="runtime" />

    <ProjectReference
      Include="..\..\external\LiveSplit\src\UpdateManager\UpdateManager.csproj"
      Private="false"
      ExcludeAssets="runtime" />

    <ProjectReference
      Include="..\LiveSplit.Bridge.Protocol\LiveSplit.Bridge.Protocol.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net4.8.1</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>

    <AssemblyName>LiveSplit.Bridge</AssemblyName>
    <RootNamespace>LiveSplit.Bridge</RootNamespace>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <DebugType>None</DebugType>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WebSocketSharp" Version="1.0.3-rc11" />
  </ItemGroup>

  <PropertyGroup>
    <BridgeDistributionFiles>LiveSplit.Bridge.dll;LiveSplit.Bridge.Protocol.dll;Google.Protobuf.dll</BridgeDistributionFiles>
  </PropertyGroup>

  <ItemGroup>
    <BridgeDistributionFile Include="$(BridgeDistributionFiles)" />
  </ItemGroup>

  <Target Name="DeployToLiveSplit" AfterTargets="Build">
    <MakeDir Directories="$(LiveSplitComponentsPath)" />

    <ItemGroup>
      <BridgeDeployFiles Include="@(BridgeDistributionFile->'$(TargetDir)%(Identity)')" />
    </ItemGroup>

    <Copy
      SourceFiles="@(BridgeDeployFiles)"
      DestinationFolder="$(LiveSplitComponentsPath)"
      SkipUnchangedFiles="true" />

  </Target>
</Project>
