<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference
      Include="..\..\external\LiveSplit\src\LiveSplit.Core\LiveSplit.Core.csproj"
      Private="false" />

    <ProjectReference
      Include="..\..\external\LiveSplit\src\UpdateManager\UpdateManager.csproj"
      Private="false" />

    <ProjectReference
      Include="..\LiveSplit.Bridge.Protocol\LiveSplit.Bridge.Protocol.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net4.8.1</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>

    <AssemblyName>LiveSplit.Bridge</AssemblyName>
    <RootNamespace>LiveSplit.Bridge</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NetMQ" Version="4.0.4.3" />
  </ItemGroup>

  <Target Name="DeployToLiveSplit" AfterTargets="Build">
    <MakeDir Directories="$(LiveSplitComponentsPath)" />

    <ItemGroup>
      <BridgeDeployFiles Include="$(TargetPath);$(TargetDir)$(TargetName).pdb" />
      <BridgeDeployFiles Include="@(ReferenceCopyLocalPaths)" />
    </ItemGroup>

    <Copy
      SourceFiles="@(BridgeDeployFiles)"
      DestinationFolder="$(LiveSplitComponentsPath)"
      SkipUnchangedFiles="true" />

  </Target>
</Project>
